docs: port user types (roles) from cluster section to administration
daytonaio/enterprise-docs pull request #110
Opened 2024-08-23 14:09 UTC by stefanicjuraj

> The user segment does not go intro cluster, rather under a new Side menu "Administration"
Under "Administration" you should add a menu User Types, and under that you should add this info

2024-08-23 21:20 UTC, stefanicjuraj commented on astro.config.mjs
> +          label: "Administration",
The above screenshot is the "administration" set as a label in the sidebar (not a standalone page) that makes the "User Types" page accessible at `/docs/administration/user-types`:

<img width="168" alt="Screenshot 2024-08-23 at 11 10 58 PM" src="https://github.com/user-attachments/assets/325cc699-1814-43e1-9a9b-09c14aee9a40">

This can also be just "administration" in the sidebar with no label making the "User Types" page accessible at `/docs/usage/administration#user-types`.

<img width="204" alt="Screenshot 2024-08-23 at 11 00 00 PM" src="https://github.com/user-attachments/assets/a7be79b6-3c59-4924-9578-a2e00da419c6">

2024-08-24 05:43 UTC, ivan-burazin commented on astro.config.mjs
> +          label: "Administration",
Very sorry this is correct:
<img width="236" alt="Screenshot 2024-08-24 at 07 43 13" src="https://github.com/user-attachments/assets/e0b02b4c-5efa-4b70-9843-393097581aef">

2024-08-24 05:43 UTC, ivan-burazin approved these changes

2024-08-28 08:57 UTC, fabjanvucina requested changes

2024-08-28 08:57 UTC, fabjanvucina commented on src/content/docs/administration/user-types.mdx
> +    Add or remove users across the entire system.
User management also includes enabling/disabling users.

2024-08-28 08:57 UTC, fabjanvucina commented on src/content/docs/administration/user-types.mdx
> +    Enable or disable Workspace classes at a global level.
This is incorrect. Workspace classes can be created or deleted.

2024-08-28 08:57 UTC, fabjanvucina commented on src/content/docs/administration/user-types.mdx
> +    Enable or disable Workspace classes at a global level.
Disclaimer: this is the current state of the workspace classes management feature.

2024-08-28 09:02 UTC, fabjanvucina commented
@ivan-burazin I stopped my review half-way because it seems like that the descriptions for the user types don't match the current state of Daytona enterprise:

- Team management is not within the scope of the global admin
- Workspace classes management is not within the scope of a team owner

I know that we have these things planned for in the near future, but should we then keep this MR on hold until these features are implemented?

2024-09-03 06:47 UTC, ivan-burazin commented on src/content/docs/installation/cluster.md
> +- **All features from Daytona Core (Single Node)**
@stefanicjuraj would remove this as its the opposite, single as all of this but runs on a single VM - also we might have to rethink naming

2024-09-03 06:48 UTC, ivan-burazin commented on src/content/docs/installation/cluster.md
> +- **Team Projects**
@stefanicjuraj dot exist yet

2024-09-03 06:49 UTC, ivan-burazin requested changes

2024-09-03 06:49 UTC, ivan-burazin commented on src/content/docs/administration/user-types.mdx
> +- **Regular User Role**
@stefanicjuraj would remove as well

2024-09-04 11:42 UTC, ivan-burazin approved these changes

2024-09-30 15:26 UTC, fabjanvucina commented
@ivan-burazin We've finalized the RBAC implementation. I outlined the initial scope for user roles [here](https://github.com/daytonaio/enterprise-docs/issues/145).

Looking at the changes in this MR, I suggest the propose changes to the docs:

1. We need to separate team-level roles from the installation-level roles
2. Installation-level roles (not sure how to call them) and their authorized actions should be taken from the linked issue description.

2024-09-30 19:39 UTC, ivan-burazin commented
@fabjanvucina do we close this one or does @stefanicjuraj finish it here?

2024-09-30 20:35 UTC, stefanicjuraj commented
I can modify the pull request with the additions commented by @fabjanvucina, and also integrate [#145](https://github.com/daytonaio/enterprise-docs/issues/145) as part of this pull request.

That way there would be all user and role-based access described within this one section.

2024-09-30 20:41 UTC, ivan-burazin commented
Lets do it

2024-10-01 08:14 UTC, fabjanvucina requested changes

2024-10-01 08:14 UTC, fabjanvucina commented on src/content/docs/administration/users.mdx
> +Daytona provides an option to view a list of all current users in the team and manage their roles and permissions. Each user is identified by their *username* and *email address*. The user list also
I would maybe scrap this paragraph. The second paragraph on its own is a great introduction to the content of the page.

2024-10-01 08:14 UTC, fabjanvucina commented on src/content/docs/administration/users.mdx
> +The Owner user role is the highest level of access in Daytona. Owners have full control over the team and can perform all administrative tasks, including managing users, Workspace classes, Identity P
> Owners have full control over the team

Owners can manage all resources and perform all administrative tasks, including ....

2024-10-01 08:14 UTC, fabjanvucina commented on src/content/docs/administration/users.mdx
> +    Assign and unassign user roles.
Assign or unassign

2024-10-01 08:14 UTC, fabjanvucina commented on src/content/docs/administration/users.mdx
> +    Enable and disable users.
Enable or disable

2024-10-01 08:14 UTC, fabjanvucina commented on src/content/docs/administration/users.mdx
> +    Create, manage, and delete Workspace classes.
Workspace classes can't be managed (updated), just created or deleted

2024-10-01 08:14 UTC, fabjanvucina commented on src/content/docs/administration/users.mdx
> +    Enable and disable users.
Enable or disable

2024-10-01 08:14 UTC, fabjanvucina commented on src/content/docs/administration/users.mdx
> +The Member role is the default user role in Daytona. Everyone added to the team is assigned the Member role by default. Members do not have administrative privileges.
Teams should not be mentioned here. We're describing global-level user roles here.

2024-10-02 17:41 UTC, ivan-burazin approved these changes

2024-10-02 21:00 UTC, fabjanvucina approved these changes

2024-10-02 21:00 UTC, merged