docs: add workspace classes description
daytonaio/enterprise-docs pull request #112
Opened 2024-08-23 22:03 UTC by stefanicjuraj

Fixes https://github.com/daytonaio/enterprise-docs/issues/94

2024-08-24 05:49 UTC, ivan-burazin requested changes

2024-08-24 05:49 UTC, ivan-burazin commented on src/content/docs/usage/workspaces.md
@stefanicjuraj these are not fixed workspace classes. Rather the Admin can create any size they want and then the user will be able to chose.

Would suggest you message it in that way that conveys there can be one or more with diff cpu/gpu/hdd/ram depedning on what the Daytona admin definedd

2024-08-24 15:11 UTC, ivan-burazin commented on src/content/docs/usage/workspaces.md
> +### Overprovisioning
This needs to go under Administration > Workspace Classes and should be removed from here

2024-08-24 15:13 UTC, ivan-burazin requested changes

2024-08-24 15:13 UTC, ivan-burazin commented on src/content/docs/usage/workspaces.md
> +- **GPU**
@stefanicjuraj all these classes are create arbitrarily so they can be call "john, mark, bob, and stan" so needs to be written in a form that the user understand what are classes not their exact name or specs

2024-08-24 22:26 UTC, stefanicjuraj commented on src/content/docs/usage/workspaces.md
> +- **GPU**
Thanks for the explanation - I have modified the description accordingly.

2024-08-24 22:32 UTC, stefanicjuraj commented on src/content/docs/usage/workspaces.md
> +### Overprovisioning
I will create a new pull request for this as there is no administration group created (merged) just yet - the administration group is created as part of the "port user types to administration" pull request [here](https://github.com/daytonaio/enterprise-docs/pull/110/files#diff-e0f0c5adbe0b9ca5d0b57caf5cea33a8d88899fd02a43df1e9862b185f8a1e5f).

2024-08-28 08:52 UTC, fabjanvucina approved these changes

2024-09-30 11:32 UTC, merged