docs: update workspace create flow
daytonaio/enterprise-docs pull request #113
Opened 2024-08-23 22:29 UTC by stefanicjuraj

Fixes https://github.com/daytonaio/enterprise-docs/issues/91

2024-08-24 05:53 UTC, ivan-burazin approved these changes

2024-08-28 08:50 UTC, fabjanvucina requested changes

2024-08-28 08:50 UTC, fabjanvucina commented on src/content/docs/usage/workspaces.md
> +In case you are creating a development container-based Workspace, you will be prompted to select the `configuration file` for your Workspace.
If the selected Git repository includes a `devcontainer.json` configuration file, you will be prompted...

2024-08-29 03:21 UTC, ivan-burazin approved these changes

2024-08-30 17:48 UTC, fabjanvucina approved these changes

2024-09-30 15:32 UTC, fabjanvucina approved these changes

2024-09-30 15:32 UTC, merged