docs: add workspaces ssh & pin sections
daytonaio/enterprise-docs pull request #114
Opened 2024-08-27 14:51 UTC by stefanicjuraj

This is a draft pull request containing initial additions and changes related to workspaces ssh connection & pinning workspaces.

Fixes https://github.com/daytonaio/enterprise-docs/issues/98
Fixes https://github.com/daytonaio/enterprise-docs/issues/96

2024-08-27 15:38 UTC, stefanicjuraj commented
In the current version of the pull request, I am missing a description/guide on how to access a Workspace via SSH (Public Key) - this option is disabled when hovering over it. Is there a way to enable it?

<img width="477" alt="Screenshot 2024-08-27 at 5 35 38 PM" src="https://github.com/user-attachments/assets/d30e62be-b719-4eb4-808d-15a50f9eecfe">

2024-08-27 15:40 UTC, stefanicjuraj commented on src/content/docs/usage/workspaces.md
> +### Public Key
In the current version of the pull request, I am missing a description/guide on how to access a Workspace via SSH (Public Key) - this option is disabled when hovering over it. Is there a way to enable it?

<img width="477" alt="Screenshot 2024-08-27 at 5 35 38 PM" src="https://github.com/user-attachments/assets/da57cfdc-67f9-4afd-bf30-26527f8504e8">

2024-08-28 06:50 UTC, ivan-burazin approved these changes

2024-08-28 08:43 UTC, fabjanvucina requested changes

2024-08-28 08:43 UTC, fabjanvucina commented on src/content/docs/usage/workspaces.md
> +4. Copy the command generated by Dayonta.
Daytonta -> Daytona

2024-08-28 08:43 UTC, fabjanvucina commented on src/content/docs/usage/workspaces.md
> +1. Copy the command generated by Dayonta.
Dayonta -> Daytona

2024-08-28 08:43 UTC, fabjanvucina commented on src/content/docs/usage/workspaces.md
> +
If a retention period is specified by the administrator, workspaces that have remained inactive longer than the retention period since they were last stopped, will be automatically deleted. Pinned workspaces will never be automatically deleted.

Administrators can set limits on the number of Workspaces that each user can pin.

2024-08-28 08:43 UTC, fabjanvucina commented on src/content/docs/usage/workspaces.md
> +
This last paragraph is possibly redundant.

2024-08-29 03:28 UTC, ivan-burazin requested changes

2024-08-29 03:28 UTC, ivan-burazin commented on src/content/docs/usage/workspaces.md
>  1. Click the pin icon next to your Workspace name to pin a Workspace.
Seems odd having just one step.

Suggestion:
1. Locate the Workspace you with to pin.
2. Click the pin icon located on the right side of Workspace name.

Or perhaps now steps at all. Open to suggestions here

2024-08-29 19:40 UTC, ivan-burazin approved these changes

2024-08-30 17:47 UTC, fabjanvucina commented on src/content/docs/usage/workspaces.md
> +
You can remove this last "Once pinned" paragraph as it repeats the explanation from a previous paragraph.

2024-09-02 11:18 UTC, fabjanvucina requested changes

2024-09-02 11:18 UTC, fabjanvucina commented on src/content/docs/usage/workspaces.md
> +
You can remove this last "Once pinned" paragraph as it repeats the explanation from a previous paragraph.

2024-09-02 14:54 UTC, fabjanvucina approved these changes

2024-09-30 11:46 UTC, merged