docs: add telemetry section
daytonaio/enterprise-docs pull request #115
Opened 2024-08-27 14:53 UTC by stefanicjuraj

This is a draft pull request containing a telemetry section addition. The telemetry section is ported from OSS documentation.

Fixes https://github.com/daytonaio/enterprise-docs/issues/102

2024-08-27 15:53 UTC, fabjanvucina commented
@stefanicjuraj The telemetry data collection feature is still pending in the enterprise product. For the time being, the telemetry section in the admin dashboard is only for giving/revoking consent.

2024-08-28 06:53 UTC, ivan-burazin requested changes
All mentions of CLI should be removed as data will be collected centeraly, which can include; cli, plugins, gui, ect.

You can confirm with @gdraganic about details

2024-08-28 06:53 UTC, ivan-burazin commented on src/content/docs/misc/telemetry.mdx
> +The goal of gathering telemetry data in the CLI is exclusively for the purpose of improving the Daytona ecosystem.
>The goal of gathering telemetry data in the CLI is
We don't collect in the CLI here but rather in generally in daytona

2024-08-29 03:21 UTC, ivan-burazin commented
adding @gdraganic to verify this.

2024-09-30 11:51 UTC, fabjanvucina commented
Commenting again for visibility. 

In the Enterprise product, telemetry data collection is a feature that hasn't yet reached the development stage. For the time being, the telemetry section in the admin dashboard is only for giving/revoking consent for when we start collecting the data.

@ivan-burazin Knowing this, how do you want to proceed with this PR?

2024-09-30 19:47 UTC, ivan-burazin commented
> Commenting again for visibility.
> 
> In the Enterprise product, telemetry data collection is a feature that hasn't yet reached the development stage. For the time being, the telemetry section in the admin dashboard is only for giving/revoking consent for when we start collecting the data.
> 
> @ivan-burazin Knowing this, how do you want to proceed with this PR?

We should say just that. "telemetry data collection is a feature that hasn't yet reached the development stage. For the time being, the telemetry section in the admin dashboard is only for giving/revoking consent for when we start collecting the data."

2024-10-02 12:19 UTC, ivan-burazin commented
@stefanicjuraj can you please update so we can merge? thanks

2024-10-02 16:21 UTC, fabjanvucina approved these changes

2024-10-02 16:21 UTC, merged