docs: add workspace samples entry
daytonaio/enterprise-docs pull request #120
Opened 2024-09-02 21:44 UTC by stefanicjuraj

Fixes https://github.com/daytonaio/enterprise-docs/issues/101

This pull request addresses the workspace samples entry. I have worded it for the single user (team member) perspective as they will be able to choose a sample that was provided to them by their team administrator - let me know if I understood this correctly.

I will add the appropriate administrator workspace samples options once the administration section is added (covered here: https://github.com/daytonaio/enterprise-docs/pull/110)

2024-09-03 06:29 UTC, ivan-burazin requested changes

2024-09-03 06:29 UTC, ivan-burazin commented on src/content/docs/usage/workspaces.md
> +     If you do not have a repository ready, you can choose to create a Workspace from a sample project provided by the administrator. This option allows you to set up a new development environment us
@stefanicjuraj I would not say "provided by the administrator" , as that would refer that someone other than the user can define this.

Rather these are added by Daytona to may user's life easier just to start.

2024-09-04 11:28 UTC, ivan-burazin approved these changes

2024-09-04 11:52 UTC, fabjanvucina approved these changes

2024-09-30 15:33 UTC, fabjanvucina approved these changes

2024-09-30 15:34 UTC, fabjanvucina commented
@stefanicjuraj Everything looks good now 👍 

We can merge this PR after you resolve the conflicts.

2024-09-30 19:32 UTC, ivan-burazin approved these changes

2024-10-01 08:00 UTC, merged