docs: modify jetbrains gateway plugin section
daytonaio/enterprise-docs pull request #126
Opened 2024-09-05 22:47 UTC by stefanicjuraj

Fixes https://github.com/daytonaio/enterprise-docs/issues/125

2024-09-06 07:01 UTC, ivan-burazin requested changes

2024-09-06 07:01 UTC, ivan-burazin commented on src/content/docs/tools/jetbrains-gateway.mdx
> +## Conclusion
Conclusion seems inconsistant with the rest of the docs so would not leave here either

2024-09-06 18:38 UTC, ivan-burazin approved these changes

2024-09-11 10:15 UTC, fabjanvucina approved these changes

2024-09-11 10:17 UTC, merged