docs: backstage plugins section
daytonaio/enterprise-docs pull request #131
Opened 2024-09-11 20:03 UTC by stefanicjuraj

Fixes https://github.com/daytonaio/enterprise-docs/issues/117
Fixes https://github.com/daytonaio/enterprise-docs/issues/129

2024-09-15 09:12 UTC, ivan-burazin commented on src/content/docs/tools/backstage-plugin.mdx
> +To integrate Daytona plugins into your existing Backstage instance, install the following plugins:
@stefanicjuraj I would remove this, and lead the reader through the set by step guide below

2024-09-15 09:14 UTC, ivan-burazin commented on src/content/docs/tools/backstage-plugin.mdx
> +Daytona Backstage Plugin is a set of integrations that enable integration of Daytona's services with Backstage. These plugins provide authentication, Workspace management, and integration capabilitie
@stefanicjuraj Repetitive update to: The Daytona Backstage Plugin integrates Daytona's services into Backstage, offering features like authentication, workspace management, and seamless interaction with Daytona Workspaces via Daytona authentication directly within Backstage.

2024-09-15 09:15 UTC, ivan-burazin commented on src/content/docs/tools/backstage-plugin.mdx
> +
Features should be updated. here is more context: https://www.daytona.io/dotfiles/daytona-enterprise-meets-backstage

2024-09-15 09:16 UTC, ivan-burazin approved these changes

2024-09-15 09:16 UTC, ivan-burazin commented on src/content/docs/tools/backstage-plugin.mdx
> +```
@stefanicjuraj feel like its missing something at the end

2024-09-20 18:46 UTC, ivan-burazin requested changes
@stefanicjuraj 
We should follow the flow of VS code plugin schema. which does include prerequisites. in this case backstage.

Also we should somewhere perhaps in the begindin a link to backstage itsself.


Also HOW TO INSTALL title and the rest of the major section should follow the other plugins.

Lastly would put backstage as the last item in the menu on the left.Ž
Thanks

2024-09-21 10:02 UTC, ivan-burazin approved these changes

2024-09-30 12:12 UTC, fabjanvucina approved these changes

2024-09-30 12:12 UTC, merged