fix: light theme flickering
daytonaio/enterprise-docs pull request #133
Opened 2024-09-16 08:58 UTC by loveloki

Change css style body.light to html[data-theme="light"] body.

Because the script appending className to the body classList is executed after the page is loaded, it causes flickering every time when enter a new page.

2024-09-29 15:26 UTC, ivan-burazin commented
@stefanicjuraj can you check if this is ok? Also if so apply to EE docs?

2024-09-30 13:04 UTC, fabjanvucina requested changes

2024-10-01 09:44 UTC, loveloki commented on src/styles/_color.scss
> +html[data-theme="light"] {
oh... it's my bad. I have fix it.

2024-10-01 09:59 UTC, fabjanvucina commented on src/styles/_color.scss
> +html[data-theme="light"] {
@loveloki Looks good! Thank you for the contribution.

2024-10-01 09:59 UTC, fabjanvucina approved these changes

2024-10-01 20:16 UTC, merged