docs: add license section
daytonaio/enterprise-docs pull request #137
Opened 2024-09-17 20:00 UTC by stefanicjuraj

Fixes https://github.com/daytonaio/enterprise-docs/issues/134

2024-09-20 19:26 UTC, ivan-burazin commented
@fabjanvucina in the Admin interface "Expires At" should be renamed to "Expiration"

@stefanicjuraj you can edit it the docs right away

2024-09-20 19:27 UTC, ivan-burazin commented on src/content/docs/administration/license.mdx
> +Adding a new License will overwrite the existing one.
@stefanicjuraj would expand a bit, something like " Daytona only supports one licence at any givien time so adding a new License will overwrite an existing one."

2024-09-20 19:27 UTC, ivan-burazin requested changes

2024-09-20 19:27 UTC, ivan-burazin commented on src/content/docs/administration/license.mdx
> +:::danger
@stefanicjuraj danger is not red?

2024-09-21 12:10 UTC, ivan-burazin approved these changes

2024-09-30 12:51 UTC, fabjanvucina approved these changes

2024-09-30 12:51 UTC, merged