docs: add quotas
daytonaio/enterprise-docs pull request #155
Opened 2024-10-04 14:47 UTC by stefanicjuraj

Fixes https://github.com/daytonaio/enterprise-docs/issues/150

2024-10-04 15:40 UTC, ivan-burazin commented
@stefanicjuraj ?

2024-10-04 20:45 UTC, ivan-burazin approved these changes

2024-10-07 11:42 UTC, fabjanvucina requested changes

2024-10-07 11:42 UTC, fabjanvucina commented on src/content/docs/configuration/teams.md
> +You can delete a team from your Daytona instance. This allows you to free up resources used under your Daytona quota, or to recreate your team from scratch.
> used under your Daytona quota

you can delete this part of the sentence

2024-10-07 11:42 UTC, fabjanvucina commented on src/content/docs/usage/usage.mdx
> +Metadata in the usage page specifies the current state of resources and quota limits. If the usage does not exist for your team, the page will display *No usage found*.
This paragraph is unnecessary

2024-10-07 11:42 UTC, fabjanvucina commented on src/content/docs/usage/usage.mdx
> +- **Filter by Workspace ID**
This should be extracted from the resources list. There should be paragraph that basically explains how to browse your workspace usage sessions.

<img width="617" alt="image" src="https://github.com/user-attachments/assets/2c1c45b6-2da9-4cf4-8cc3-7ec740a0d1ee">

2024-10-07 11:42 UTC, fabjanvucina commented on src/content/docs/administration/quotas.mdx
> +- **Workspace Credits**
If left unspecified, workspace usage will not be limited within the quota. (phrase it however you think is best)

2024-10-07 11:42 UTC, fabjanvucina commented on src/content/docs/administration/quotas.mdx
> +
Same as workspace credits -> unspecified = unlimited

2024-10-07 11:42 UTC, fabjanvucina commented on src/content/docs/administration/quotas.mdx
> +    Optionally, specify the maximum number of Workspaces that can be pinned by the user.
Same as workspace credits -> unspecified = unlimited

2024-10-07 11:42 UTC, fabjanvucina commented on src/content/docs/administration/quotas.mdx
> +Removing the Quota will prevent the creation of new Workspaces within that Quota. Existing Workspaces will not be affected.
Removing the quota will affect the teams to which it was applied. These teams will lose access to resources until a different quota is applied to them.

2024-10-08 09:29 UTC, fabjanvucina requested changes

2024-10-08 09:29 UTC, fabjanvucina commented on src/content/docs/usage/usage.mdx
> +View the resources usage within your current quota limits by accessing the **`Usage`** page in the dashboard sidebar. You will be presented with metadata specifying the current state of resources, us
_View the resources usage within your current quota limits by accessing the **`Usage`** page in the dashboard sidebar. Additionally, you can view the history of your Workspace usage sessions._

2024-10-08 09:29 UTC, fabjanvucina commented on src/content/docs/administration/quotas.mdx
> +- **Workspace Credits**
If left empty, the Workspace _credits_ will not be limited by the Quota.

2024-10-08 09:29 UTC, fabjanvucina commented on src/content/docs/administration/quotas.mdx
> +
If left empty, the _number of_ parallel Workspaces will not be limited by the Quota.

2024-10-08 09:29 UTC, fabjanvucina commented on src/content/docs/administration/quotas.mdx
> +    Optionally, specify the maximum number of Workspaces that can be pinned by the user. If left empty, the pinned Workspaces will not be limited by the Quota.
If left empty, the _number of_ pinned Workspaces will not be limited by the Quota.

2024-10-08 15:26 UTC, fabjanvucina approved these changes

2024-10-08 15:26 UTC, merged