docs: add cursor ide
daytonaio/enterprise-docs pull request #156
Opened 2024-10-04 16:05 UTC by stefanicjuraj

Fixes https://github.com/daytonaio/enterprise-docs/issues/152

2024-10-04 20:50 UTC, ivan-burazin requested changes

2024-10-04 20:50 UTC, ivan-burazin commented on src/content/docs/usage/ide.mdx
>  You can set the default IDE used by Daytona. Daytona allows you to connect to your development environment using a variety of IDEs, including popular options like Visual Studio Code (VSCode) and JetB
@stefanicjuraj the issue with cursor is if you are in the dashboard i full screen you wont see the prompt, but rather have to go to your desktop - please try to see. thanks

2024-10-05 05:53 UTC, ivan-burazin approved these changes

2024-10-07 11:43 UTC, fabjanvucina approved these changes

2024-10-07 11:46 UTC, merged