docs: add identity providers (admin) & modify identity providers (install)
daytonaio/enterprise-docs pull request #157
Opened 2024-10-04 23:56 UTC by stefanicjuraj

Fixes https://github.com/daytonaio/enterprise-docs/issues/123

2024-10-06 13:02 UTC, ivan-burazin approved these changes

2024-10-07 11:53 UTC, fabjanvucina requested changes
@ivan-burazin We no longer need instructions on how to use Keycloak for managing identity providers. The admin dashboard in Daytona now fully supports management of these providers.

@stefanicjuraj You should transfer over instructions on how to create oauth applications for each IDP from the /installation/identity-providers page. After that, you can remove that page from the docs.

2024-10-07 13:49 UTC, fabjanvucina commented
@stefanicjuraj Also, the redirect URI field has been added to the IDP form.

<img width="1046" alt="image" src="https://github.com/user-attachments/assets/9823b273-aa2f-42c7-8646-a887b7115157">

2024-10-07 19:05 UTC, ivan-burazin requested changes
@stefanicjuraj what is the diff with INSTALLATION IDPs and ADMIN IDPs

2024-10-07 19:09 UTC, stefanicjuraj commented
> @stefanicjuraj what is the diff with INSTALLATION IDPs and ADMIN IDPs

There will only be administration identity providers for admins to be able to enable certain identity providers, and the users can refer to using them by navigating to the git providers section. I think that's the main gist provided by Fabijan's thoughts:

> @stefanicjuraj You should transfer over instructions on how to create oauth applications for each IDP from the /installation/identity-providers page. After that, you can remove that page from the docs.

2024-10-08 05:31 UTC, ivan-burazin commented
Yes so we should delete the section under INSTALLATION then?

2024-10-08 09:37 UTC, fabjanvucina requested changes

2024-10-08 09:37 UTC, fabjanvucina commented on src/content/docs/index.mdx
>    <DocumentListItem
Remove this list item

2024-10-08 09:37 UTC, fabjanvucina commented on src/content/docs/administration/identity-providers.mdx
> +
@stefanicjuraj For each IdP, we need the instructions on how to create the OAuth app.

These instructions were already written in `src/content/docs/installation/idps.mdx`, they just need to ported into this new page.

Example (github):

3. **Configure GitHub as an Identity Provider**
- Under the default realm, click on **`Identity Providers`** under the *Configure* section on the left sidebar.
- Then click on **`github`**. On the next page, copy the **`Redirect URI`** and note it down, as we will need it later. *Don't close this tab*.

4. **Go to Developer Settings**
- Open [Github](https://github.com) in your browser, on the top right side of this page, click on your profile picture. Under the dropdown window, select **`Settings`** (at the bottom). Select **`Developer setting`s** on the left sidebar.

5. **Create OAuth Apps**
- Select the **`OAuth Apps`** on the left sidebar. Then click on **`New OAuth App`** on the top right side.

6. **Required Inputs for GitHub OAuth**

- For the application name, you can name it as easily recognizable for yourself and distinguish it from your other applications (recommend using deployed domain).
- The **`Homepage URL`** would be the URL to your Daytona dashboard.
- The **`Authorization callback URL`** is the URL you have copied from step 2, `Redirect URI`. You don't need to toggle `Enable Device Flow` here. Then click on **`Register application`**.

7. **Copy Client ID and Secrets**
- Under your application, click on the **`Generate a new client secret`** in the *Client secrets* section.
- Copy the **`credentials under Client ID`** and paste it into your Keycloak *Provider details* page in the Client ID section.
- Go back to the Github OAuth Application page, copy the **`credentials under the Client secrets`** section, and then paste it into *Client Secret* on your Keycloak *Provider details* page.

Of course, these instructions have to be reworded wherever Keycloak is mentioned.

2024-10-11 15:27 UTC, stefanicjuraj commented on src/content/docs/administration/identity-providers.mdx
> +
The old version of installation/idps section now has some outdated or missing identity providers, such as Azure Active Directory (Microsoft Entra), Azure DevOps, and Microsoft.

I still need to update the docs to reflect the new configuration of identity providers.

2024-10-12 13:56 UTC, ivan-burazin commented
@stefanicjuraj ping me when review needed

2024-10-17 18:40 UTC, ivan-burazin approved these changes

2024-10-23 16:15 UTC, fabjanvucina requested changes

2024-10-23 16:15 UTC, fabjanvucina commented on src/content/docs/administration/identity-providers.mdx
> +Upon adding GitHub as an Identity Provider, you can configure GitHub OAuth to enable users to authenticate with Daytona using their GitHub account.
Before adding GitHub as an Identity Provider, you need to register an OAuth client to enable users to authenticate to Daytona using their GitHub account.

_make this change in all of the providers_

2024-10-23 16:15 UTC, fabjanvucina commented on src/content/docs/administration/identity-providers.mdx
> +### GitHub OAuth
GitHub OAuth Client

2024-10-23 16:15 UTC, fabjanvucina commented on src/content/docs/administration/identity-providers.mdx
> +    - `Authorization callback URL` must be set to the `Redirect URI` used when connecting GitHub as an Identity Provider.
must be set to the `Redirect URI` value found in the form when adding GitHub as an Identity Provider.

2024-10-23 16:15 UTC, fabjanvucina commented on src/content/docs/administration/identity-providers.mdx
> +
We need an another item here that says that the user should copy over the client id and the client secret values to finalize adding GitHub as an IdP.

Please make sure that these "GitHub" changes are reflected accordingly in other IdPs as well

2024-10-23 16:15 UTC, fabjanvucina commented on src/content/docs/administration/identity-providers.mdx
> +
There needs to be info where to find client_id, client_secret and tenant_id and that they need to be copied over to the form for adding the IdP

2024-10-23 16:15 UTC, fabjanvucina commented on src/content/docs/administration/identity-providers.mdx
> +
This logic applies for other IdP-s as well. Also, keep in mind that some IdP-s have specific config properties (for example tenant_id for Azure)

2024-10-26 16:25 UTC, ivan-burazin commented
@fabjanvucina are we good with this?

2024-10-30 12:37 UTC, merged