docs: update git providers
daytonaio/enterprise-docs pull request #160
Opened 2024-10-06 18:27 UTC by stefanicjuraj

Fixes https://github.com/daytonaio/enterprise-docs/issues/128

2024-10-06 18:59 UTC, ivan-burazin requested changes
<img width="577" alt="Screenshot 2024-10-06 at 20 58 27" src="https://github.com/user-attachments/assets/59cde529-4747-430e-94c7-b019a5636c15">
<img width="521" alt="Screenshot 2024-10-06 at 20 58 23" src="https://github.com/user-attachments/assets/2d3c33ab-ddeb-4244-9721-cfe2472fb2e8">
@stefanicjuraj missing some providers

2024-10-06 19:05 UTC, ivan-burazin reviewed
@stefanicjuraj still missing azure devops

2024-10-06 19:07 UTC, ivan-burazin approved these changes

2024-10-07 11:57 UTC, fabjanvucina requested changes
@stefanicjuraj Should be connect/disconnect git provider, not add/remove

2024-10-08 09:40 UTC, fabjanvucina approved these changes

2024-10-08 09:40 UTC, merged