docs: modify about section
daytonaio/enterprise-docs pull request #175
Opened 2024-10-14 23:15 UTC by stefanicjuraj

Fixes https://github.com/daytonaio/enterprise-docs/issues/165

2024-10-15 18:45 UTC, ivan-burazin requested changes

2024-10-15 18:45 UTC, ivan-burazin commented on src/content/docs/about/what-is-daytona.mdx
> +Daytona supports deployments across multiple environments, including cloud-hosted platforms, self-managed infrastructure, and open source solution.
this entire section should be delated and updated: 

Daytona is an open-source Development Environment Management platform designed to enhance developer productivity and experience. By automating the entire setup process, Daytona creates unified and standardized development environments, reducing the burden on your DevOps team by handling the orchestration of these environments.

With flexible deployment options, Daytona offers Open Source, Cloud, and Self-managed solutions, empowering organizations to tailor their infrastructure choices. This versatility enables organizations to optimize their technology investments and enhance operational efficiency.

2024-10-16 18:59 UTC, ivan-burazin approved these changes

2024-10-23 16:24 UTC, fabjanvucina approved these changes

2024-10-23 16:24 UTC, merged