docs: add offerings availability label
daytonaio/enterprise-docs pull request #179
Opened 2024-10-15 16:40 UTC by stefanicjuraj

Fixes https://github.com/daytonaio/enterprise-docs/issues/173

2024-10-15 16:42 UTC, stefanicjuraj commented
@ivan-burazin

2024-10-15 17:48 UTC, ivan-burazin commented on src/content/docs/administration/license.mdx
> +  Distribution: **Cloud**, **Self-Managed**
@stefanicjuraj how is licence available in Cloud? This is just for Self managed as cloud users have "billing"

2024-10-15 17:48 UTC, ivan-burazin commented on src/content/docs/administration/quotas.mdx
> +  Distribution: **Open Source**, **Cloud**, **Self-Managed**
@stefanicjuraj plus update the designs to the figma file. thanks

2024-10-15 17:49 UTC, ivan-burazin commented on src/content/docs/administration/quotas.mdx
> +  Distribution: **Open Source**, **Cloud**, **Self-Managed**
@stefanicjuraj the entire admin section is not available on Cloud or OSS

2024-10-15 17:53 UTC, ivan-burazin requested changes

2024-10-15 17:53 UTC, ivan-burazin commented on src/content/docs/installation/cluster.mdx
> +<Label>
@stefanicjuraj these three installation options are only visible to self manged

2024-10-15 17:53 UTC, ivan-burazin commented on src/content/docs/misc/telemetry.mdx
> +  Distribution: **Open Source**, **Cloud**, **Self-Managed**
@stefanicjuraj telemetry is not available on cloud

2024-10-15 17:53 UTC, ivan-burazin commented on src/content/docs/tools/jetbrains-gateway.mdx
> +  Distribution: **Cloud**, **Self-Managed**
@stefanicjuraj available on all three

2024-10-17 18:40 UTC, ivan-burazin requested changes
- All Installation is only self Managed
- Usage is not OSS
- Settings is cloud and self managed
- CLI is all

2024-10-30 12:40 UTC, fabjanvucina commented
@stefanicjuraj Before we merge, can you check if there are new pages (from recently merged PRs) that are missing the offerings label

2024-11-06 10:26 UTC, fabjanvucina approved these changes

2024-11-06 10:26 UTC, merged